### ISSUE TITLE
Alien::Build doesn't list Sort::Versions as a dependency

### ISSUE THREAD

**Issue by djerius** [PerlAlien/Alien-Build#242] opened 2020-11-12 22:50 UTC
When developing with `Alien::Build` (not when working with a distribution tar ball), `Sort::Version` needs to be explicitly installed, as `Alien::Build` doesn't specify it as a dependency. 

I'm using `Dist::Zilla::Plugin::AlienBuild` in my [`dist.ini`](https://gitlab.com/djerius/Alien-XPA/-/blob/master/dist.ini).  `Alien::Build` is listed in the project's [`cpanfile`](https://gitlab.com/djerius/Alien-XPA/-/blob/master/cpanfile)

Attached is a  [`Dockerfile`](https://github.com/PerlAlien/Alien-Build/files/5533630/Dockerfile.txt) to replicate the issue. Here's the output:
```
$ podman build -t dzil-test -f Dockerfile.txt 
STEP 1: FROM debian:10
STEP 2: RUN	apt-get update &&                               apt-get -y upgrade &&                           apt-get -y install                                  perl                                            perl-base                                       perl-doc                                        perl-modules                                    cpanminus                                       gcc                                             tar                                             curl                                	    libterm-readline-gnu-perl           	    libwww-perl                          	    make                                	    git
--> Using cache b26025ab12d8a12709ee13a050557bec52508fe06f815b903ae316653b824f36
--> b26025ab12d
STEP 3: RUN	apt-get -y install                                  emacs-nox
--> Using cache e6d0d603e5c4fa073dbc1e6c57af0aa02389be47f0ba77322e2535e4414ea64f
--> e6d0d603e5c
STEP 4: ENV	TAR_OPTIONS=--no-same-owner
--> Using cache b3038fa4b38aa7466509ece720c96985df2f846dc295ab8864f66fb21a994deb
--> b3038fa4b38
STEP 5: RUN     cpanm Dist::Zilla
--> Using cache b144d828092c9fbe8945f385352502a8377f1a832e134380d9f88ed7e58febb5
--> b144d828092
STEP 6: WORKDIR /tmp
--> Using cache eda50621f1de438354bcae96af5f615ec163444e5085175ec1d25acc43fe9bc9
--> eda50621f1d
STEP 7: RUN     git clone https://gitlab.com/djerius/Alien-XPA.git
--> Using cache 6b800a68cd84db54e2a7f191c7a81cf58d38a0adbaba22c18729a341152d014e
--> 6b800a68cd8
STEP 8: WORKDIR /tmp/Alien-XPA
--> Using cache a6b2a514540bbea1323db41a79743eabb81e0de3c6a38ca9a77484901e8dbae8
--> a6b2a514540
STEP 9: RUN     dzil authordeps --missing | cpanm
--> Using cache b845b510bd73d1b8ce3f4a5e0e7e49042fe28b49dad07f0dbdd8d4102b03f123
--> b845b510bd7
STEP 10: RUN	cpanm --installdeps --with-develop .
--> Using cache 65d59c96bcd46dadc70fb7e484e36aab59574ef4bfbdbdc6a42b9d7cf2ba7a3a
--> 65d59c96bcd
STEP 11: RUN     dzil test
[DZ] building distribution under .build/a8et_NI4fw for installation
[DZ] beginning to build Alien-XPA
[DZ] guessing dist's main_module is lib/Alien/XPA.pm
[DZ] writing Alien-XPA in .build/a8et_NI4fw
[ReadmeAnyFromPod] overriding README.mkdn in root
[EnsurePrereqsInstalled] dynamic_config is set: make sure you put all possible prereqs into develop prereqs so your tests are complete!
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Alien::Build::CommandSequence> + pkg-config --exists xpa
Can't exec "pkg-config": No such file or directory at /usr/local/share/perl/5.28.1/Alien/Build/CommandSequence.pm line 87.
Alien::Build> error in probe (will do a share install): external command failed at /usr/local/share/perl/5.28.1/Alien/Build/CommandSequence.pm line 88.
Alien::Build> Don't panic, we will attempt a share build from source if possible.
Alien::Build> Do not file a bug unless you expected a system install to succeed.
Checking if your kit is complete...
Looks good
Warning: prerequisite Sort::Versions 0 not found.
Generating a Unix-style Makefile
Writing Makefile for Alien::XPA
Writing MYMETA.yml and MYMETA.json
cp lib/Alien/XPA.pm blib/lib/Alien/XPA.pm
"/usr/bin/perl" -MAlien::Build::MM=cmd -e prefix site /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Can't locate Sort/Versions.pm in @INC (you may need to install the Sort::Versions module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/share/perl/5.28.1/Alien/Build.pm line 317.
make: *** [Makefile:1024: _alien/mm/prefix] Error 2
error running make
Error: error building at STEP "RUN dzil test": error while running runtime: exit status 2
```

**Comment by Grinnz** [comment] 2020-11-12 22:54
It is added as a dynamic dependency when needed. The problem is you are using the cpanfile to install dependencies, rather than the configuration. I solve this by 1. ensuring the repository contains copies of Makefile.PL+META.json so cpanm can use them to configure it properly, 2. either running cpanm with `--cpanfile=nonexistent`, or avoiding using a cpanfile at all to specify that dist's prereqs, either specifying them with https://metacpan.org/pod/Dist::Zilla::Plugin::Prereqs or https://metacpan.org/pod/Dist::Zilla::Plugin::PrereqsFile.

**Comment by Grinnz** [comment] 2020-11-12 22:56
Also since you're using dzil already, you can get the correct configured list of deps to install with [dzil listdeps](https://metacpan.org/pod/Dist::Zilla::App::Command::listdeps).

**Comment by Grinnz** [comment] 2020-11-12 23:06
Looking at your configuration, you are already specifying prereqs with [Prereqs], but you are generating a cpanfile which is confusing cpanm. I recommend not generating the cpanfile, and adding META.json to the files you are copying from the release.

**Comment by Grinnz** [comment] 2020-11-12 23:14
I'm happy to discuss/debug your dzil config more on irc.perl.org #native or #distzilla by the way :)

**Comment by djerius** [comment] 2020-11-13 00:32
> Looking at your configuration, you are already specifying prereqs with [Prereqs], but you are generating a cpanfile which is confusing cpanm. I recommend not generating the cpanfile, and adding META.json to the files you are copying from the release.

Thanks.  It seems `META.json` gets `Sort::Versions`, but doesn't get any of the developer prereqs, and `cpanfile` gets the developer prereqs, but not `Sort::Versions`.  Sigh.  I can make things work if I run `cpanm` both using  `cpanfile` and with the `--cpanfile=nonexistent` trick you pointed out.

I'll close this as NOTABUG

> I'm happy to discuss/debug your dzil config more on irc.perl.org #native or #distzilla by the way :)

Thanks.  I'll take you up on that in a bit (although the real time connection requirements of IRC to get messages is a pain point for me).  

[ TBH, I've spent enough time on this issue by working through [this](https://github.com/containers/podman/issues/8320#event-3990740795) and coaxing my linux box to get systemd to create a session for NIS based logins so that I can run `podman` again that I'm going to take a rest from infrastructure for a bit.]

**Comment by plicease** [comment] 2020-11-13 09:16
I don't recommend shipping a `cpanfile` with AB based Aliens because I have found the dynamic prereqs with the `cpanfile` can sometimes confuse installers.  You can specify configure, build-share and build-system prereqs in the `alienfile` itself, and the `[AlienBuild]` plugin should correctly set the static configure + dynamic build prereqs correctly, and the runtime prereqs are usually just AB itself.

The `af missing` command will list the missing dynamic prereqs with just the `aleinfile` and without having to build with dzil.

```
af missing -p configure | cpanm
af missing | cpanm 
```

App::af is a fairly heavy dep though so you may not want to install that in a container.

**Comment by djerius** [comment] 2020-11-13 16:33
> You can specify configure, build-share and build-system prereqs in the `alienfile` itself, and the `[AlienBuild]` plugin should correctly set the static configure + dynamic build prereqs correctly, and the runtime prereqs are usually just AB itself.

If I understand things correctly, this advice ensures that the required _non-developer_ prereqs are listed in `META.json`, and my experiments (noted above) indicate that reality mirrors that.

I've been using `cpanfile` as it lists the developer pre-reqs, and my experiments indicate that `META.json` (as generated by my `dzil` setup) doesn't. (The context is that I'd like there to be enough metadata in the source repo so that one doesn't need `dzil` to build it, and `cpanfile` has seemed to work.)

I think I can solve my problems if I can figure out how to get `dzil` to include the developer pre-reqs in `META.json` and thus get rid of `cpanfile`.

**Comment by Grinnz** [comment] 2020-11-13 16:43
Develop phase prereqs will be included fine, but cannot be dynamic. I'm not sure what you mean by META.json doesn't include them.

**Comment by Grinnz** [comment] 2020-11-13 16:44
Dynamic prereqs are not up to META.json. Makefile.PL will be run to determine them, which the AlienBuild plugin will set up to generate correctly.

**Comment by djerius** [comment] 2020-11-13 17:38
Sorry, ignore my last comment.  I'm getting my experiments and their results confused at the moment.

**Comment by plicease** [comment] 2021-09-29 15:35
> I think I can solve my problems if I can figure out how to get `dzil` to include the developer pre-reqs in `META.json` and thus get rid of `cpanfile`.

You can use [Prereqs](https://metacpan.org/pod/Dist::Zilla::Plugin::Prereqs) or [PrereqsFile](https://metacpan.org/pod/Dist::Zilla::Plugin::PrereqsFile).  I believe that AB is working as designed here, although some documentation changes may be useful here, so I am closing this now.

**Closed by plicease** 2021-09-29 15:35 UTC
